# Generated by Django 5.2 on 2025-04-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="custom_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
