# Generated by Django 5.2 on 2025-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0002_clients_custom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="profile_img",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
