# Generated by Django 5.2 on 2025-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customuser_full_name_customuser_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_img",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
