name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /opt/myproject/myproject/alex_ai

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Activate virtualenv, install dependencies, migration, restart server
      run: |
        source /opt/myproject/bin/activate
        cd /opt/myproject/myproject/alex_ai/
        git stash
        git pull origin main
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
        python manage.py migrate
        sudo pkill gunicorn || true
        sudo systemctl restart nginx.service
        nohup gunicorn --bind 0.0.0.0:8000 xinfo_ai.wsgi &
