name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /opt/myproject/myproject/alex_ai

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Activate virtualenv and install dependencies
      run: |
        source /opt/myproject/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: |
        source /opt/myproject/bin/activate
        python manage.py collectstatic --noinput

    - name: Run migrations
      run: |
        source /opt/myproject/bin/activate
        python manage.py migrate

    - name: Restart Gunicorn
      run: |
        pkill gunicorn || true
        nohup gunicorn --chdir /opt/myproject/myproject/alex_ai xinfo_ai.wsgi:application --bind 0.0.0.0:8000 &
